project_id = "kmbckriozzpsuxblzhot"

[auth.hook.send_email]
enabled = true
uri = "https://kmbckriozzpsuxblzhot.supabase.co/functions/v1/custom-email"

[functions.custom-email]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false

[functions.get-recaptcha-sitekey]
verify_jwt = false

[functions.bootstrap-superadmin]
verify_jwt = false

[functions.approve-admin]
verify_jwt = false

[functions.opname-notify]
verify_jwt = false
